### ISSUE TITLE
Remove `browserify` parameter/command

### ISSUE THREAD

**Issue by janpio** [apache/cordova-lib#676]
This was previously discussed that this parameter/command was never fully implemented or used, so it can safely be removed.

Side effect:
This will also remove the dependency to `cordova-js` in `cordova-lib` (if I didn't miss anything).

**Comment by raphinesse** [comment]
> This will also remove the dependency to `cordova-js` in `cordova-lib` (if I didn't miss anything).

Nice :+1:

**Comment by sommcz** [comment]
Hello, is there any suggested replacement for this removed functionality?

I used this parameter for bundling cordova.js & plugins js into single file (for simple deployment of different version to hosted cordova app).

Thank you

**Comment by raphinesse** [comment]
@sommcz Unfortunately, I can only guess what your exact use case is. Can't you simply concatenate those two files?

I would suggest you ask that question in our slack channel, with additional details.
