### ISSUE TITLE
Limit `requireCordovaModule` to Cordova modules

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova-lib#689]
## The Context

The context provided to hooks has a method called `requireCordovaModule`.

https://github.com/apache/cordova-lib/blob/1bc9dd050cbc12b046fd7e20628084d79d2f9fe4/src/hooks/Context.js#L50-L72

The apparent purpose of this method is to allow users to require modules of the exact version of Cordova that is running the hook. I guess that makes some sense, given how we currently use the Node module system to provide singletons.

## The Problem

However, this method conceptually leaks all internals of `cordova-lib`, including any of its dependencies, to the hooks context. In fact, the [only documentation on this method](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/#javascript) even **encourages** users to use it to require Q, which we could break, if we removed Q from our dependencies as part of #681. I can see how this might have seemed like a great idea when promises weren't available in native JS, but that has thankfully changed now.

## The Solution

I suggest we limit the modules allowed to import using `Context.prototype.requireCordovaModule` to a fixed whitelist containing only `cordova-*` dependencies of `cordova-lib` and `cordova-lib` itself.

As a first step, we should only issue a deprecation warning if anything not on the whitelist is required.

As an additional safety measure, we might warn users about using private interfaces when they deep-require something (like `require('cordova-lib/src/hooks/Context')` for example).

What do you think? I'm looking forward to your feedback.

**Comment by raphinesse** [comment]
After #706, I'm beginning to think we should consider rolling out the deprecation step even earlier than the next major.

**Comment by brodybits** [comment]
I would personally favor starting the deprecation now and limiting `requireCordovaModule` to Cordova modules in the next major.

**Comment by brodybits** [comment]
Shouldn't we consider dropping support for `requireCordovaModule('cordova-lib')` or `requireCordovaModule('*/cordova-lib')` altogether?

**Comment by raphinesse** [comment]
> Shouldn't we consider dropping support for `requireCordovaModule('cordova-lib')` or `requireCordovaModule('*/cordova-lib')` altogether?

I'm not sure what you mean by `requireCordovaModule('*/cordova-lib')`. After #709, The argument for `requireCordovaModule` must be either the name of a Cordova package (`cordova-*`) or a path to a module in a Cordova package (`cordova-*/**`).

In case you meant we should drop the method altogether: I actually considered that. But as long as the predominant usage of `cordova-lib` & Co. is through a globally installed package `cordova` I think we need a means for people to require modules from the _currently executing_ version of Cordova. Which is exactly what `requireCordovaModule` provides.

---

That being said, I would prefer that people require `cordova-lib` or `cordova` as a dependency in their projects and use only that to build them. That way regular `require` would pick up the right versions of everything and it would be perfectly clear which version of Cordova is required to build a project.
