### ISSUE TITLE
plugman test flaky after GH-691 (cordova-windows@~6.0.0)

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-lib#695]
From <https://github.com/apache/cordova-lib/pull/691#issuecomment-421951927> (comment on a merged PR):

After merging GH-691 (cordova-windows@~6.0.0) we see an AppVeyor CI failure on Node.js 10 (passed on Node.js 6 & 8). The change proposed in GH-691 *did* pass AppVeyor CI before it was merged.

I suspect this is another case of flaky tests (#642).

**Comment by janpio** [comment]
> The change proposed in GH-691 did pass AppVeyor CI before it was merged.

#691 doesn't list any CI checks being run: https://github.com/apache/cordova-lib/pull/691/checks Am I missing something? Were those removed after merge?

Right now it seems to me the test is _consistently_ failing since #691.

**Comment by raphinesse** [comment]
@janpio you have to click "View Details" where it says that the PR has been merged.

**Comment by raphinesse** [comment]
@brodybits @janpio Links to the test failures in the CI logs would be helpful.

**Comment by raphinesse** [comment]
Curiously, Travis CI was configured to only test with Node 4 and 6 when cordova-windows 6 was tagged

**Comment by janpio** [comment]
Failing tests on merge to `master` are at https://ci.appveyor.com/project/Humbedooh/cordova-lib/build/1.0.2814/job/pbmia5soyvei4bc4. Same test failures for PRs started after that commit (e.g. https://github.com/apache/cordova-lib/pull/696)

**Comment by raphinesse** [comment]
@janpio I created #698 for those. But these tests do not even use `cordova-browser`. They use `cordova-android` as a test platform

**Comment by janpio** [comment]
I don't even fake that I understand what the tests are doing - so I'm just happy you both seem to have found a way to fix this 💯

**Comment by brodybits** [comment]
Latest commit in `master` is now green, closing now. I hope this will solve the failure on #696.

**Comment by janpio** [comment]
Rebased #696 onto `master` including #698 indeed did fix the build. 
Thanks @raphinesse and @brodybits.
