### ISSUE TITLE
symlink is used when adding local plugin in windows

### ISSUE THREAD

**Issue by knight9999** [apache/cordova-lib#701]
When we add local plugin as
```
cordova plugin add /path/to/local_plugin/
```
in windows environment, a `symlink` is created.

I feel that a `junction` should be created. Becuase `npm` command creates a `junction` in windows. 

My question is that symlink in windows is ok?

I checked this by using `cordova-cli` 8.1.x in github with `cordova-lib@9.0.0-nightly.2018.9.20.63b26e63` in npm.

```
> ..\cordova-cli\bin\cordova.cmd -v
8.0.1-dev (cordova-lib@9.0.0-nightly.2018.9.20.63b26e63)
>  ..\cordova-cli\bin\cordova.cmd plugin add ..\..\plugins\cordova-plugin-camera
```

The result is following. (Here I add cordova-plugin-camera downloaded to my local PC)

```
> dir node_modules
2018/09/20  18:36    <DIR>          .
2018/09/20  18:36    <DIR>          ..
2018/09/20  18:36    <JUNCTION>     cordova-plugin-camera [C:\Users\knaito\Documents\work\cordova\plugins\cordova-plugin-camera]
```
The node_module is `junction` pointing to the original directory. (This is ok)

```
> dir plugins
2018/09/20  18:36    <DIR>          .
2018/09/20  18:36    <DIR>          ..
2018/09/20  18:36    <SYMLINK>      cordova-plugin-camera [C:\Users\knaito\Documents\work\cordova\plugins\cordova-plugin-camera\]
2018/09/20  18:36               241 fetch.json
```
The plugin is `symlink` pointing to the original directory. (Is this ok?)

**Comment by raphinesse** [comment]
I guess the main reason why a `junction` should be preferred over a `symlink` in this case is that a user needs to have special privileges to create a `symlink` while this is not true for a `junction`. Correct? Are there other reasons why one should be preferred over the other?

**Comment by janpio** [comment]
Oh hi @knight9999, I just found your [StackOverflow question](https://stackoverflow.com/questions/52361940/fs-stat-function-for-symlink-pointing-to-directory-in-windows) and this issue when googling for the error messages in https://github.com/apache/cordova-lib/issues/704

For me this is causing problems as `fs.existsSync` crashes with an error message, I also can't follow the symlink with PowerShell or Cmder - only git bash.

Your comment above gave me the idea to check:

```
C:\Users\Jan\AppData\Local\Temp\cordova-lib-plugin_dependency_test-Sm2ttG\project>dir plugins
 Volume in drive C is System
 Volume Serial Number is 1C2A-94E2

 Directory of C:\Users\Jan\AppData\Local\Temp\cordova-lib-plugin_dependency_test-Sm2ttG\project\plugins

2018-09-21  14:29    <DIR>          .
2018-09-21  14:29    <DIR>          ..
2018-09-21  14:29               341 android.json
2018-09-21  14:29    <DIR>          cordova-plugin-file
2018-09-21  14:29    <DIR>          cordova-plugin-whitelist
2018-09-21  14:29               578 fetch.json
2018-09-21  14:29    <SYMLINK>      Test1 [C:\Projects\experiments\cordova-cross-spawn-test\cordova-lib\spec\plugman\plugins\dependencies\Test1\]
               3 File(s)            919 bytes
               4 Dir(s)  13,884,665,856 bytes free

C:\Users\Jan\AppData\Local\Temp\cordova-lib-plugin_dependency_test-Sm2ttG\project>cd Test1
The system cannot find the path specified.

C:\Users\Jan\AppData\Local\Temp\cordova-lib-plugin_dependency_test-Sm2ttG\project>
```

Manually using `cd C:\Projects\experiments\cordova-cross-spawn-test\cordova-lib\spec\plugman\plugins\dependencies\Test1\` (the path of the symlink) works though as it should.

**Comment by oliversalzburg** [comment]
> I guess the main reason why a junction should be preferred over a symlink in this case is that a user needs to have special privileges to create a symlink while this is not true for a junction. Correct?

That is correct. A symlink on Windows can even specify remote targets and should still generally be avoided on Windows. Junctions serve the same purpose a symlink would on a UNIX.

**Comment by knight9999** [comment]
Thanks @janpio @oliversalzburg .
I guessed that mixed use of `junction` and `symlink` is unfavorable.
This is solved by @oliversalzburg 's PR https://github.com/apache/cordova-lib/pull/705 
where copy is used instead of link.

**Comment by knight9999** [comment]
Thanks you everyone.
I close this issue.

**Comment by oliversalzburg** [comment]
I full agree with that conclusion.

**Comment by raphinesse** [comment]
After merging #705, do we still need to take any further action to fix this?

**Comment by knight9999** [comment]
Thanks @oliversalzburg 
I feel #705 solves this issue. We have nothing to do any further action! @raphinesse

**Comment by knight9999** [comment]
I further checked Windows Server 2012 R2 which is same in appveyor.
fs.stat can work for symlink pointing to other directory.
👎
