### ISSUE TITLE
platformsConfig.json links to old/broken git repositories via `url`

### ISSUE THREAD

**Issue by janpio** [apache/cordova-lib#702]
https://github.com/apache/cordova-lib/blob/63b26e630c8adb6918a4c7c28e10905e24807eab/src/platforms/platformsConfig.json#L4-L32

these `url`s don't work any more. 
Are they not needed or used anywhere and can be removed maybe?

**Comment by raphinesse** [comment]
I asked myself the same question before. Thanks for creating this issue, Jan.

**Comment by brodybits** [comment]
I think it would be worth testing with "url" entries removed. Easiest solution may be to simply update them for GitHub.

**Comment by raphinesse** [comment]
URLs have been updated
