### ISSUE TITLE
Add Promise.try polyfill

### ISSUE THREAD

**Issue by dpogue** [apache/cordova-lib#713]
There are a bunch of places that we're using a pattern like `return Promise.resolve().then(...)` which has a very slight async penalty and can make stacktraces a bit harder to read.

We should replace these with a `Promise.try` polyfill, like [proposal-promise-try](https://github.com/tc39/proposal-promise-try) or [p-try](https://www.npmjs.com/package/p-try).

**Comment by xeoneux** [comment]
I'd like to give it a try

**Comment by raphinesse** [comment]
Once we drop support for Node.js 6 it's probably better to use `async` functions instead of any `Promise.try` implementation.

**Comment by raphinesse** [comment]
Closing in favor of apache/cordova#175
