### ISSUE TITLE
Support Tizen operating system in Cordova CLI

### ISSUE THREAD

**Issue by pkosko** [apache/cordova-lib#715]
Dear Cordova Community,
I am engineer working in Samsung R&D Center and developer of Web Device API of Tizen. I would like to encourage you to join the discussion about supporting Tizen as one of available platforms in Cordova CLI. 

The main goal of such extension is to wider the market for Cordova application developers, who could easily deploy application to the next platform - Tizen. As I did some research that to support 'tizen' in CLI there is a need to update several packages on git e.g.:
- cordova-lib
- cordova-serve
- cordova-tizen
and the changes rather need to be done at the same time in all of them (the procedure of adding such related changes is not known to me, I did not find any clues about that).

The huge plan is also adding Tizen-specific implementation for most common Cordova plugins. 

Unfortunately, I didn't find any detailed information about supporting new platform in Cordova (probably it is not very popular case), so I would like to discuss it here and gather all comments from you - more experienced Cordova developers.

Could you please share your thoughts and suggestions of the best ways of adding Tizen platform to Cordova?

**Comment by dpogue** [comment]
There is a [Cordova-Tizen platform](https://github.com/apache/cordova-tizen) from a few years ago, but it has not been maintained and is currently unusable. In theory, there shouldn't be any required changes to cordova-lib, and the bulk of the initial work will be updating cordova-tizen to use the new Platform API.

I'd encourage you to send an email to the [dev mailing list](https://cordova.apache.org/contact/) to discuss further.

The situation with the existing Tizen plugin is that contributions dropped off and there was nobody knowledgeable enough about Tizen to review pull requests, test releases, or generally provide the ongoing maintenance that it needed.

**Comment by raphinesse** [comment]
Here is the [mailing list thread](https://lists.apache.org/thread.html/5ab6969a95578d0ba6339a5d17f401deb52a5d37f12f5ae35404185c@%3Cdev.cordova.apache.org%3E) for reference. We would love to hear any updates regarding your endeavor.

I'm going to close this issue as there is nothing we can do here in `cordova-lib`.
