### ISSUE TITLE
Missing support for installing plugins from subdirectories

### ISSUE THREAD

**Issue by janpio** [apache/cordova-lib#722]
https://github.com/apache/cordova-lib/pull/624/files#diff-357b50ca17711373bcd14d32725ff069R69 removed support for installing things from subdirectories.

This broke the documented way to install plugin tests: https://github.com/apache/cordova-plugin-test-framework#tldr-try-it

The `:subdir` snytax is also still documented at https://github.com/apache/cordova-cli/blob/master/doc/readme.md#plugin-spec

Is this just not possible any more or was this usage overlooked?

**Comment by janpio** [comment]
The case "I want to install the tests of my plugins" can be solved with these commands, as the tests are checked out with the plugin themselves:

```
cordova plugin add https://github.com/apache/cordova-plugin-file-transfer.git
cordova plugin add plugins/cordova-plugin-file-transfer/tests
```

**Comment by janpio** [comment]
https://github.com/apache/cordova-lib/pull/624#discussion_r236045164

@dpogue said:

> That :subdirectory syntax was specific to the old Cordova fetching code (which has been removed), and is not supported by npm

**Comment by janpio** [comment]
Submitted a PR to `cordova-plugin-test-framework` that replaces theses commands with working ones (besides other things):
https://github.com/apache/cordova-plugin-test-framework/pull/29

CLI docs should be updated then as well?

**Comment by undersieg** [comment]
I'm also unable to install plugin which has local dependency specified by url="." and subdir="some/local/path/from/git/root"

**Comment by raphinesse** [comment]
I'm closing this, as the `cordova-plugin-test-framework` use-case is resolved and we will not provide installation options that exceed what npm can do.

@undersieg please create an issue with more detailed information if your problem persists.
