### ISSUE TITLE
`cordova requirements android` crashes - `this.isCordova is not a function`

### ISSUE THREAD

**Issue by bluetech** [apache/cordova-lib#740]
I left a comment here explaining what I believe is the problem: https://github.com/apache/cordova-lib/commit/af1a1b519ce792451875be438b7a795806445899#diff-82ee48eb5f4bcbbd61e7573c641594e3R36

Changing `this.isCordova` to `cordova_util.isCordova` fixes the problem for me.

**Comment by brodybits** [comment]
Thanks @bluetech. It would also be good if we can add a unit test to cover this case.
