### ISSUE TITLE
user specified override for config.xml

### ISSUE THREAD

**Issue by bdirito** [apache/cordova-lib#746]
Version info is specified in config.xml. In our build process this is ephemeral data [based on git tags]. Config.xml however cannot be ephemeral as it also contains things such as <preference> tags. 

It would be nice if we could provide explicit values for things such as android-versionCode on `cordova prepare`. Given that that particular field doesnt even have meaning beyond one platform I expect the cleanest way to do something would be to allow cordova prepare to specify the location of config.xml. 

```
cordova prepare --config=config.tmp.xml
```

It looks like https://github.com/apache/cordova-lib/blob/master/src/cordova/util.js#L263 is the place that would have to be modified.

**Comment by dpogue** [comment]
Not exactly what you're asking for, but potentially a solution: I wrote a helper tool called [seymour](https://www.npmjs.com/package/seymour) for our CI system to allow setting app ID, version, name, and other preferences via environment variables.

**Comment by raphinesse** [comment]
@bdirito Could you solve your issue using `seymour`?

**Comment by brodybits** [comment]
We are not really interested in the proposed enhancement since we already have a solution. In case someone can explain why our solution is not good enough for a use case then we would be happy to discuss and consider supporting another solution. Closing for now, at least.
