### ISSUE TITLE
cordova 9.0.0 plugin add not saving to config.xml

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-lib#756]
# Bug Report

### What is expected to happen?
config.xml to be added  `<plugin name="cordova-plugin-whatever" spec="^1.0.0" />`

### What does actually happen?
config.xml not updated

## Information

After doing `cordova plugin add cordova-plugin-whatever` the plugin is added to the project and builds properly but the config.xml at root of project is not updated (it is not plugin dependent, hence "whatever")

### Command or Code

`cordova plugin add cordova-plugin-whatever`

### Environment, Platform, Device

cordova-lib 9.0.0
cordova-android 7.1.4
windows 10

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by dpogue** [comment]
This is by design: Cordova 9 does not save plugins or platforms to config.xml. They are saved to package.json instead.

They will be restored from both package.json and config.xml, but the intention is to push people towards using package.json for storing these dependencies.

**Comment by hunterloftis** [comment]
In that case, why does the default-generated "hello, world" app in cordova 9 supply its default whitelist plugin in config.xml but not in package.json?

**Comment by timbru31** [comment]
Because it needs to be updated ;)  
The issue is already tracked here: https://github.com/apache/cordova-app-hello-world/issues/39

**Comment by dandouglas** [comment]
Phonegap build relies on the plugins to be listed in the config.xml though which is an issue.

**Comment by globules-io** [comment]
Let me vocalize my opinion on this change again. This is a very bad design. Both files should be kept in sync, or one file should go. As a matter of fact, package.json is a NPM thing, where config.xml is a Cordova thing. I don't see the point AT ALL to merge these 2 files. Whoever made that "design" needs to reconsider his/her involvement in this scale of a projects.

**Comment by kim3er** [comment]
My have been debugging an issue with my remote builds, which turned out to be missing plugins.

I'm using Cordova v9, but the project started life at v4. The issue I faced was that plugins that existed locally, weren't being installed when built in the cloud (using Azure DevOps).

All the plugins were listed in package.json, but config.xml only included a partial list. The cloud build was only installing the partial list from config.xml.

Removing all the entries in config.xml resulted in no plugins being installed.

Manually listing all the plugins from package.json into config.xml resulted in all plugins being installed.

The build environment is macOS latest, Node 8.6.4. The package.json version of Cordova is ^9.0.0. All the scripts use Cordova in a local context. Cordova, to the best of my knowledge, is not installed globally.

My GIT repo has the follow Cordova related exclusions:

```
platforms/
plugins/
plugins/android.json
plugins/ios.json
www/
```

**Comment by codegreenie** [comment]
Let me say i have faced same issue. Normally when you add a plugin from CLI, it should be added to config.xml for the sake of Phonegap build...This is very confusing for an inexperienced programmer and i am considering rolling back to Cordova CLI 8.1.0

**Comment by dpogue** [comment]
@codegreenie If you're working with PhoneGap Build, I'd recommend using the [phonegap CLI tool](https://www.npmjs.com/package/phonegap) rather than the cordova CLI tool.

**Comment by acedigibits** [comment]
this is super confusing now. i used to add res/icon paths in config.xml , will all those settings remain in config.xml and only plugins moving to package.json ?

**Comment by dpogue** [comment]
> will all those settings remain in config.xml and only plugins moving to package.json ?

Yes, only the dependencies (plugin and platform versions) are moving to package.json. All your app configuration continues to live in config.xml.

**Comment by globules-io** [comment]
> Let me say i have faced same issue. Normally when you add a plugin from CLI, it should be added to config.xml for the sake of Phonegap build...This is very confusing for an inexperienced programmer and i am considering rolling back to Cordova CLI 8.1.0

For us, it is mostly that when you open config.xml you see everything, you know exactly where you at with the project. Like for instance, you see custom preferences and all the plugin stuff  in config.xml and you see if the plugins are installed etc without opening package.json, which can also have stuff non related to cordova (that you might use for the front end). It way easier to know what's going on with your project. Package.json can become hard to read.

As long as you don't remove the plugin detection in config.xml, here we are ok since we keep on using config.xml for plugins since it's so much easier to copy paste from one config.xml to the other in case of multi apps.




 You don't need to open packages.json
