### ISSUE TITLE
requireCordovaModule + shelljs

### ISSUE THREAD

**Issue by robertnicjoo** [apache/cordova-lib#782]
# Bug Report

## Problem

I'm trying to make test app for windows platform with ionic but it returns this error

## Information

```
Using "requireCordovaModule" to load non-cordova module "shelljs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
```

### Command or Code

```
ionic cordova build windows
```

### Environment, Platform, Device
Windows 10

### Version information

Ionic 5
Cordova 9.0.0 (cordova-lib@9.0.1)
VS 2019
VS Code

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by dpogue** [comment]
This is an issue that needs to be fixed in a plugin or hook. It is not an error with Cordova itself.

**Comment by robertnicjoo** [comment]
@dpogue my app is very basic the only plugin i installed is cordova barcodescanner so I'm not sure really where this error comes from. Can you at least tell me where i can add `require shelljs` in order to see if this error resolve or not?

**Comment by janpio** [comment]
In the plugin, as @dpogue said.

**Comment by erisu** [comment]
@robertnicjoo If your using the `phonegap/phonegap-plugin-barcodescanner` plugin, there is already a PR to fix this but has not been merged or released yet. Please wait until this PR is merged and a new release of the plugin is available. https://github.com/phonegap/phonegap-plugin-barcodescanner/pull/780

**Comment by robertnicjoo** [comment]
@erisu thanks man, yes that's the plugin that i used I guess i'll just wait till that pr merged.
