### ISSUE TITLE
e2e test of pkg.json update for local path fails on AppVeyor CI

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-lib#787]
# Bug Report

## Problem

The end-to-end test of `pkg.json` update for local path fails on AppVeyor CI on Node.js version 10. The failing test is in the following function: https://github.com/apache/cordova-lib/blob/c5e1722d03a7d916f6060cde93b0929847ab20a3/integration-tests/pkgJson.spec.js#L256-L278

The proposed workaround in PR #786 is to skip this test on Windows.

The correct solution is to investigate *why* this test fails on AppVeyor CI on Node.js 10 and resolve the underlying cause.

I am raising this issue as asked by @janpio in <https://github.com/apache/cordova-lib/pull/786#issuecomment-501610109>.

### What is expected to happen?

This end-to-end test succeeds on AppVeyor CI on all supported Node.js versions.

### What does actually happen?

This end-to-end test fails on AppVeyor CI on Node.js version 10.

## Information

In <https://github.com/apache/cordova-lib/commits/master> we can see that the build failed on 268688a6c059ed648af8d043cf3303bcd75c0df2 - the failure is on AppVeyor CI on Node.js version 10.

This build failure appeared when I raised and then merged PR #783. Unfortunately I did not see the failure before merging that PR.

I tried raising PR #785 to revert PR #783, but reverting PR #783 does not seem to resolve this test failure.

### Command or Code

See `appveyor.yml`: the following command seems to reproduce this failure on AppVeyor CI: `npm test`

### Environment, Platform, Device

Windows server on AppVeyor CI

### Version information

See `package.json`:

- cordova-common@3
- cordova-create@2
- cordova-fetch@2
- cordova-serve@2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by brodybits** [comment]
While filling in the information requested by the issue template, I realized that cordova-lib is still using fs-extra@7. I wonder if using fs-extra@latest (fs-extra@8) may resolve this test failure?

I will try with fs-extra@8 after we publish cordova-common@3.2.0, also with fs-extra@8 update, in 12-18 hours.

**Comment by brodybits** [comment]
Bad news: fs-extra@8 update does not seem to resolve the issue on Node.js 10: https://ci.appveyor.com/project/brodybits/cordova-lib/builds/25272793/job/srv776acvnxsxvrb

for cordova-common@3-nightly and fs-extra@8 updates: https://github.com/apache/cordova-lib/compare/master...brodybits:fs-extra-8-nightly-wip

I think we need the test workaround that I proposed in PR #786. I remain very hopeful that we can resolve this AppVeyor CI issue, someday.

**Comment by raphinesse** [comment]
This was resolved by #770
