### ISSUE TITLE
cordova 9.0.0 plugin add not saving plugin in dependency list

### ISSUE THREAD

**Issue by WuglyakBolgoink** [apache/cordova-lib#794]
# Bug Report

### What is expected to happen?

```
{
  "devDependencies": {
    "cordova-plugin-whitelist": "1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  },
  "dependencies": {
    "cordova-android": "8.0.0",
    "cordova-ios": "5.0.1",
    "cordova-plugin-device": "a.b.c" <<<<<<<<<<<<<<< I need this line
  }
}
```

### What does actually happen?

-  add plugin

```bash

cordova plugins add cordova-plugin-device --save
```

-  open `package.json`
```
{
  "devDependencies": {
    "cordova-plugin-whitelist": "1.3.4"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  },
  "dependencies": {
    "cordova-android": "8.0.0",
    "cordova-ios": "5.0.1"  <<<<<<<<< missed  "cordova-plugin-device": "a.b.c"
  }
}
```

## Information
```
cordova-lib@9.0.1 with:
  cordova-common@3.2.0
  cordova-create@2.0.0
  cordova-fetch@2.0.1
  cordova-serve@3.0.0

Environment: 
  OS: darwin
  Node: v10.16.0
  npm: 6.9.0
```

**Comment by WuglyakBolgoink** [comment]
and I can't understand why some plugins will be stored in dependency block, and other not...

**Comment by breautek** [comment]
Is this still an issue?

This appears to work for me:

```bash
cordova create test test.cordova.app
cd test
cordova plugins add cordova-plugin-device
vim package.json
```

I see in my `package.json` file:

```json 
"dependencies": {
        "cordova-plugin-device": "^2.0.3"
},
```

**Comment by WuglyakBolgoink** [comment]
@breautek I check this in next days...

**Comment by gNazi** [comment]
Shouldn't "requireCordovaModule" be replaced since cordova 9 doesn't support it anymore ?!

**Comment by gNazi** [comment]
> > Shouldn't "requireCordovaModule" be replaced since cordova 9 doesn't support it anymore ?!
> 
> `requireCordovaModule` is still used.
> 
> But there are many plugins that used it wrong. It should only be used to import cordova modules. Using `requireCordovaModule` to require non-cordova modules such as the (`q` package) is no longer supported as of cordova 9.

True, as im getting this error when trying to build:
`Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`

Only problem is I can't find the code at fault, i've searched my entire project and the plugins i've used for it !

**Comment by breautek** [comment]
> > > Shouldn't "requireCordovaModule" be replaced since cordova 9 doesn't support it anymore ?!
> > 
> > 
> > `requireCordovaModule` is still used.
> > But there are many plugins that used it wrong. It should only be used to import cordova modules. Using `requireCordovaModule` to require non-cordova modules such as the (`q` package) is no longer supported as of cordova 9.
> 
> True, as im getting this error when trying to build:
> `Using "requireCordovaModule" to load non-cordova module "fs" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.`
> 
> Only problem is I can't find the code at fault, i've searched my entire project and the plugins i've used for it !

This issue is not related to the issue you're commenting on. I'll provide some guidance, but if you have anymore questions, please open a new support ticket.

Likely a plugin you're using. Perhaps using it in an obscure way like `requireCordovaModule(someVariable)`. I'd recommend loosening you're search keywords. Can even  modify `requireCordovaModule` to print out a stacktrace to help pinpoint to the source. (It might already do this if you use the `--verbose` flag).

**Comment by raphinesse** [comment]
Closing this as we could not reproduce the issue and haven't heard back from @WuglyakBolgoink. If you could reproduce the issue, please let us know how.
