### ISSUE TITLE
Improve how Cordova checks for required project information

### ISSUE THREAD

**Issue by brodybits** [apache/cordova-lib#829]
As reported in <https://github.com/apache/cordova/issues/155>, Cordova stops with an error message if there is no `www` directory. I have seen cases where this behavior is not really wanted. Some developers want to have third-party tools such as Ionic, Angular, or Webpack generate the entire `www` directory as part of the build process, within a hook script for example.

Another thing is that newer versions of Cordova will not work if there is no `package.json` file. As discussed in <https://github.com/apache/cordova-cli/issues/498>, Cordova CLI reports a confusing error message if there is no `package.json` file.

I think Cordova should be updated to check for the required configuration in `config.xml` and `package.json`, and only require `www` when it is ready to prepare, build, or run a project.

**Comment by raphinesse** [comment]
Since this issue affects multiple repositories, I am going to close this in favor of https://github.com/apache/cordova/issues/155
