### ISSUE TITLE
cordova prepare not resolving platform specification correctly for devDependency

### ISSUE THREAD

**Issue by grunthor** [apache/cordova-lib#832]
# Bug Report

## Problem
when running `cordova prepare ` for a project with a platform as a devDependency in the package.json, the version is not discovered correctly.

The manual moving of the platform from dependencies to devDependencies is suggested by the verbose logging of cordova-fetch and issues apache/cordova-fetch#64 and apache/cordova-electron#88. 

And the changes from pull request apache/cordova-fetch#65 will result in the platforms being added to devDependencies by default.
### What is expected to  #happen?
With
```
"dependencies": {
},
"devDependencies": {
    "cordova-electron": "^1.1.1"
},
```
running `cordova prepare` after removing platforms, should fetch cordova-electron ^1.1.1
expected console log (this occurs if the platform is in dependencies):
```
Discovered platform "electron@^1.1.1" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-electron@^1.1.1
```
### What does actually happen?
instead, this tries to fetch cordova-electron ^1.0.0
actual console log:
```
Discovered platform "electron" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-electron@^1.0.0
```
## Information
This seems to be a result of an if else construct the addHelper.js
https://github.com/apache/cordova-lib/blob/master/src/cordova/platform/addHelper.js#L96-L108
It looks like this finds an empty dependencies object, and then does not subsequently check the devDependencies object contents at all.

### Command or Code
reproduction method: (courtesy of @erisu )
```
cordova create electronTest
cd electronTest/
$ cordova platform add electron
Using cordova-fetch for cordova-electron@^1.0.0

$ cordova prepare
[Cordova Electron] The built package size may be larger than necessary. Please run with --verbose for more details.

rm -rf platforms

$ cordova prepare
Discovered platform "electron@^1.1.1" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-electron@^1.1.1

rm -rf platforms

vi package.json
/// HERE I am moving to devDependencies

$ cordova prepare
Discovered platform "electron" in config.xml or package.json. Adding it to the project
Using cordova-fetch for cordova-electron@^1.0.0
```

### Environment, Platform, Device
Running on Windows 7

### Version information
Cordova 9.0.0 (cordova-lib@9.0.1)

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by Crono1981** [comment]
I think this should be reopened. The same thing happens with Android@10.1.0. The prepare command will go and fetch Android@9.1.0.

As a workaround I've added the platform as a runtime dependency rather than a development dependency (using the --save option with `cordova platform add`).
