### ISSUE TITLE
One test fails on CI

### ISSUE THREAD

**Issue by raphinesse** [apache/cordova-lib#863]
### What is expected to happen?
CI is green

### What does actually happen?
CI is red (see CI runs for https://github.com/apache/cordova-lib/pull/862)

## Information

There seems to be unexpected behavior in our automated test suite: package.json was modified during plugin installation when it shouldn't have been because `save` option was not given. I wanted to check the last build logs for master (which were green) but they did not load for me on the Travis CI website.

Thus I'm leaving this here, in case someone has time to investigate.

**Comment by timbru31** [comment]
Log attached from (https://travis-ci.org/github/apache/cordova-lib/jobs/733538294)
[log.txt](https://github.com/apache/cordova-lib/files/5628209/log.txt)
