### ISSUE TITLE
Question About API 24 And API 30 And Question About How Make Jar Using Cordova 9.1.0 And Cordova 10.0.0 (Solution for jcenter() deprecated)

### ISSUE THREAD

**Issue by BirdDodo32** [apache/cordova-lib#875]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [ x] Support Question

## Description
I Have 2 Problem, And I'm Sorry, I write in one issue.

1. **I try running my application using emulator API 24 and running well.** but in Emulator with API 30 my application not running well, the problem is when i scrolling page to down, my page jump into top middle. some times when i scroll down, the scroll direction not into down, but top.
I confused, because this application running very well in API 24. 

this problem coming from my code or in browser i dont know, can you give me some explanation, maybe. so that i can trace my code.
2. I Try to make jar using Cordova 9.1.0 and Cordova 10.0.0 because jcenter() deprecated, and in mavencentral() Cordova still not exist. when i try to compile and make jar using Cordova 9.1.0 i found error in the part of code below(bold code). i using Java 1_8. 
When i try to make jar using Cordova 10.0.0, i found error in all code that using androidX. Do you have any solution for this problem?

I try hard to make this question, because my english not good. Hope you understand with my question, Thank You..
## Information

For Question 1. I using framework7 to design my application, and i using some plugins like sqlite, and other. Using Cordova 9.0.0

### Command or Code

Code For Question 2.
public Object postMessage(String id, Object data) {
        LOG.d(TAG, "postMessage: " + id);
        synchronized (this.pluginMap) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                **this.pluginMap.forEach((s, plugin) -> {** 
                    if (plugin != null) {
                        plugin.onMessage(id, data);
                    }
                });
            } else {
                for (CordovaPlugin plugin : this.pluginMap.values()) {
                    if (plugin != null) {
                        Object obj = plugin.onMessage(id, data);
                        if (obj != null) {
                            return obj;
                        }
                    }
                }
            }
        }
        return ctx.onMessage(id, data);
    }

### Environment, Platform, Device

minSdkVersion 24
targetSdkVersion 30
Using Cordova 9.0.0

### Version information

Android studio, Framework7 V1

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by jcesarmobile** [comment]
Cordova-android is on mavencentral now
