### ISSUE TITLE
Why cordova-android 12.0.0 is not used ?

### ISSUE THREAD

**Issue by sestienne** [apache/cordova-lib#919]
Hi, 

A version of cordova-android 12.0 is available. Why cordova-lib uses cordova-android 11 and not cordova-android 12 (cf package.json) ?

**Comment by erisu** [comment]
That is a dev dependency that is not used in production releases.

It is only used when testing lib. Cordova-Android 12 was not even released at the time.

It will be updated eventually but shouldn't have high priority since its a lib test. Not platform.

I will close out this ticket.
