### ISSUE TITLE
plugins skipped on cordova-ios 8.0.0.beta.1 due to failed version requirement

### ISSUE THREAD

**Issue by svanlang** [apache/cordova-lib#936]
# Bug Report

## Problem

When adding the cordova ios- 8.0.0.beta1 platform i get this notion on a number of plugins. e.g.

- Plugin doesn't support this project's cordova-ios version. cordova-ios: 8.0.0-beta.1, failed version requirement: >=6.0.0 
- Plugin doesn't support this project's cordova-ios version. cordova-ios: 8.0.0-beta.1, failed version requirement: >=5.1.0 Skipping PLUGIN NAME for ios

### What is expected to happen?

plugin should be added since cordova-ios: 8.0.0 is larger then the required version

### What does actually happen?

I get above mention +  Skipping PLUGIN NAME for ios
this happens for instance on the cordova-plugin-camera plugin. 

### Command or Code

cordova platform remove ios 
cordova platform add ios@8.0.0-beta.1

### Environment, Platform, Device

iPad, iOS 18
develop platform Mac OS 15.1 (24B83)

### Version information
Cordova iOS 8.0.0 Beta1 

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

**Comment by erisu** [comment]
I am closing out this ticket as we just released `cordova-lib@12.0.2` that resolved this issue.

To get this release, just reinstall the Cordova CLI 12.x and it will checkout the new lib package.

If Cordova CLI is installed globally:

```
npm uninstall -g cordova
npm install -g cordova@latest
```

If Cordova CLI is installed locally within your project:

```
npm uninstall cordova
npm install cordova@latest
```

To confirm that `cordova-lib@12.0.2` was checked out, run `cordova -v` command and confirm the printout:

```
$ cordova -v
12.0.0 (cordova-lib@12.0.2)
```
